language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

env:
  - QT_BASE=56

before_install:
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt56-trusty -y; fi
  - sudo apt-get update -qq

install:
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi

script:
  - qmake src/QMaterialIcons.pro
  - make

notifications:
  email: false
